version: "3.9"

services:

  db:
    image: mysql:8
    container_name: smart_db
    restart: always
    env_file: .env
    ports:
      - "3307:3306"
    volumes:
    - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend-service:
    build: ./backend-service
    container_name: backend
    depends_on:
      - db
    env_file: .env
    ports:
      - "8001:8000"

  ai-service:
    build: ./ai-service
    container_name: ai_service
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8002:8000"
