services:

  db:
    image: mysql:8
    container_name: smart_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smart_classroom
    ports:
      - "3307:3306"
    volumes:
    - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend-service:
    build: ./backend-service
    container_name: backend
    depends_on:
      - db
    env_file: .env
    ports:
      - "8001:8000"

  ai-service:
    build: ./ai-service
    container_name: ai_service
    ports:
      - "8002:8000"
